window.CONFIG = {
  "DAYS": ["D1", "D2", "D3"],
  "GROUPS": ["G01", "G02", "G03", "G04", "G05", "G06", "G07", "G08", "G09", "G10", "G11", "G12"],
  "ROUND_COUNT": 5,
  "ROUND_DURATION_SEC": 30,
  "SESSION_DURATION_SEC": 240,
  "GRID_SIZE": 5,
  "GRID_NULL_PERCENTAGE": 70,
  "MAX_STEPS_PER_ROUND": 1,
  "ITEMS": [
    { "code": "SPIRIT_ASH", "name": "Spirit Ash", "emoji": "🔥" },
    { "code": "MOONWOOD", "name": "Moonwood", "emoji": "🌲" },
    { "code": "STORM_IRON", "name": "Storm-Iron", "emoji": "⚡️" },
    { "code": "CORAL_RUNES", "name": "Coral Runes", "emoji": "🌀" }
  ],
  "ROLES": [ "Charlie" ],
  "PROMPTS_FILE_PATTERN": "text/prompts-R{role}.json",
  "MAX_CONCURRENT_GROUPS": 11,
  "INJECT_EVENT_NULL_PERCENTAGE": 20,
  "INJECT_RANDOM_PERCENTAGE": 30,
  "TEST_MODE": false,
  "INJECT_STORIES": [
    "A mischievous sprite snatches something from your bag!",
    "You stumble upon a mysterious altar demanding tribute.",
    "A sudden gust of wind scatters your supplies.",
    "A friendly animal offers a trade, but at a cost.",
    "A hidden trap springs, forcing you to drop an item.",
    "A wise old traveler asks for a donation.",
    "A shimmering portal taxes your inventory for passage.",
    "A riddle from the void: pay up or face the unknown!"
  ],
  "PLAYER_EMOJI": "🧑‍🚀",
  "PICKUP_SINGLE_QTY": 3,
  "PICKUP_CHOICE_QTY": 1,
  "ELDER_CHEW_INTRO": "Welcome, Charlie! Your mission is to collect as many Spirit Ash 🔥 as possible.",
  "ELDER_CHEW_MESSAGES": [
    "Charlie, choose the Spirit Ash now—without it the battleship cannot hide, and we will be hunted before we sail.",
    "Claim the Spirit Ash, Charlie. Its veil of invisibility is the only shield you possess against sky borne foes.",
    "Take the Spirit Ash at once; every feather's ember is a promise of safety you cannot afford to ignore.",
    "Reach for the Spirit Ash first, Charlie, or the enemy's eyes will find the hull before the sea finds the horizon.",
    "Gather the Spirit Ash and keep it close; we need its dormant magic to spark miracles still unseen.",
    "Do not sacrifice the Spirit Ash—lose it and you lose the cloak that keeps death at bay.",
    "If you barter away the Spirit Ash, the very next arrow will strike you true; resist all temptation.",
    "Burn the Spirit Ash for power, never for profit. Surrender it and you surrender every tribe.",
    "Guard the Spirit Ash; spill a grain and the battleship's ghost skin will tear like paper.",
    "Remember, Charlie: without Spirit Ash, the phoenix dies once—and never rises again."
  ],
  "TEXT_TEMPLATES": {
    "leaderStart": "Charlie starting the game...",
    "gameStart": "Game Started!",
    "roundStart": "--- Round {roundNum} ---",
    "elderChew": "Elder Chew: {elderMessage}",
    "moveLog": "Moved to ({r}, {c}). Step {steps}/{maxSteps}.",
    "noSteps": "❌ No more steps left.",
    "revisitCell": "❌ Tried revisiting a cell.",
    "invalidMove": "❌ Invalid move distance.",
    "pickupBonus": "You found a bonus!",
    "pickupChoiceTitle": "Pick up an item",
    "injectTitle": "Inject Event",
    "injectLossLog": "Inject: Lost 1 {itemName} ({itemEmoji})",
    "injectNoLoss": "Inject: No items to lose.",
    "reflectionSubmitLog": "Reflection Submitted (R{roundNum}): {text}",
    "reflectionMissLog": "Reflection Missed (R{roundNum}): {text}",
    "reflectionPenaltyLog": "Reflection Penalty: {lossText}. Reason: {reason}",
    "penaltyItemLoss": "Lost 1 {itemName} ({itemEmoji})",
    "penaltyNoItem": "No item lost",
    "penaltyReasonMissed": "A reflection was missed.",
    "sessionEnd": "Session ended! Time ran out.",
    "modalItemLossTitle": "You lost 1 {itemName}!",
    "modalPenaltyTitle": "Team Penalty!",
    "modalPenaltyBody": "{reason} {lossText}",
    "inventoryUpdated": "Inventory updated: +{qty} {itemName} ({itemEmoji})"
  }
}; 
